# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      # Checks out your repository so your job can access it.
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8' # Choose the Python version suitable for your project.
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller
        # Add other dependencies here or use pip install -r requirements.txt if you have one.
        
    - name: Run Python script
      run: python infant_mortality.py
      # This will execute your Python script.
      
    - name: Compile Python script to executable with PyInstaller
      run: pyinstaller --onefile infant_mortality.spec
      # Compiles your Python script into a single executable using the spec file.
      
    # Optional: Validate HTML files
    - name: Validate HTML files
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        npm install -g html-validator-cli
        html-validator --file=index.html
        html-validator --file=infant_mortality.html
      # Validates your HTML files using the html-validator-cli package.

